name: Greeting on variable day

on:
  issues:
    types: [opened, edited, milestoned]

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "${{ github.event.pull_request.title }}"
        env:
          First_Name: Mona
